### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by floriangbh** [hakopako/PKNotification#10]
Hello,

Firstly, thank you for this library, I'm using it in multiple project.

When i'm trying to use PKNotification with Cocoapod I found issue, for exemple : "Module PKNotification as no member named loading'.

To make this error : 
- pod 'PKNotification', '~> 1.0'
- import PKNotification in my swift file 

What I need to do ? 

Thank you :) 

PS : Can you update for Swift 3.0 ? :)

**Comment by apognu** [comment]
Same issue here, is there any chance of fix?

This library is unusable as is.
