### ISSUE TITLE
tons of errors with Xcode 6.3

### ISSUE THREAD

**Issue by moheny** [hakopako/PKNotification#5]
I A big fan of PKNotification since it's came up, but since the new update of Xcode 6.3 i'm getting tons of errors like 
"// MARK: - Lifecycle
    required override init() {
        super.init()
    }"
is there any fix around it ?

**Comment by hakopako** [comment]
Hi, thanks for reporting this error.
I fixed them in [this commit](https://github.com/hakopako/PKNotification/commit/31df82a67a23e153fb96499aaf73d1d838bb77c0).
Hopefully It works!
