### ISSUE TITLE
Dyn Framework

### ISSUE THREAD

**Issue by MetalheadSanya** [hakopako/PKNotification#7]
Please, add framework scheme to your library and add this to CocoaPods and Carthage

**Comment by hakopako** [comment]
Hi, @MetalheadSanya 
Sorry for this TOOO late reply.
but I will update and make it adapt to CocoaPods, possibly Carthage soon.

Thanks.

**Comment by hakopako** [comment]
Hi, @MetalheadSanya 
I've added PKNotification to CocoaPods and Carthage.
Please check new release tag [v1.0](https://github.com/hakopako/PKNotification/tree/v1.0)

**Comment by MetalheadSanya** [comment]
Thanks very much) I test this in our next project
