### ISSUE TITLE
any update to (Xcode 7.1 Swift 2.1)

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [hakopako/PKNotification#8]
Hi @hakopako ,

Your notification library was so great, I'm using it in my applications. Just want to know if are you considering to update this in the latest Xcode and Swift versions ?

Thanks.

**Comment by hakopako** [comment]
Hi @rjjohnpatrickcruz .
Thank you so much using my library. I'm really happy to hear that.
Honestly, I didn't expect someone using it happily.
now I can see some demand of it, so I will update it soon or later,

Thanks.

**Comment by rjjohnpatrickcruz** [comment]
Hi @hakopako,

Thanks for responding! I'm happy to hear that! I'm looking forward for your update. Hope you could notify me once you implement it.

Thank you!

Cheers!

**Comment by hakopako** [comment]
@rjjohnpatrickcruz 

I've updated PKNotification in Xcode7.x , Swift2.x.
Please check new release tag [v1.0](https://github.com/hakopako/PKNotification/tree/v1.0).

**Comment by rjjohnpatrickcruz** [comment]
Hi @hakopako,

Thanks! will try this.

Cheers!
